# Generated by Django 5.1.1 on 2024-10-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=180)),
                ('image', models.ImageField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(default='', max_length=50)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
