# Generated by Django 5.1.1 on 2024-10-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_email',
            new_name='usuario_email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_age',
            new_name='usuario_idade',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_nickname',
            new_name='usuario_nickname',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_name',
            new_name='usuario_nome',
        ),
    ]
