# Generated by Django 5.1.3 on 2024-12-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
