# Generated by Django 5.1.1 on 2024-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_rename_descricao_postagem_post_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_nickname',
            new_name='usuario_username',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_senha',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_sobrenome',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nome',
            field=models.CharField(default='', max_length=20),
        ),
    ]
