# Generated by Django 4.2.16 on 2024-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_profilereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereport',
            name='reason',
            field=models.TextField(default='Motivo não especificado', verbose_name='Motivo do Report'),
        ),
    ]
