# Generated by Django 5.1.1 on 2024-10-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
