# Generated by Django 5.1.1 on 2024-10-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_alter_comentario_options_alter_postagem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
