# Generated by Django 5.1.1 on 2024-10-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_alter_postagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={},
        ),
    ]
