# Generated by Django 5.1.1 on 2024-10-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_alter_comentario_options_alter_postagem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_recebidos', to='aplic.usuario')),
            ],
        ),
    ]
