# Generated by Django 5.1.1 on 2024-10-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='criado_em',
            new_name='Report_criado_em',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='motivo',
            new_name='Report_motivo',
        ),
        migrations.AlterField(
            model_name='report',
            name='usuario_reportado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to='aplic.usuario'),
        ),
    ]
