# Generated by Django 5.1.1 on 2024-10-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_rename_criado_em_report_report_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Report_motivo',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_biografia', models.TextField(default='', max_length=150)),
                ('perfil_interesses', models.CharField(default='', max_length=50)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.usuario')),
            ],
        ),
    ]
