# Generated by Django 5.1.1 on 2024-10-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0015_alter_report_report_motivo_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
